apiVersion: v1
kind: Namespace
metadata:
  name: konga
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  namespace: konga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        name: konga
        app: konga
    spec:
      nodeSelector:
        kubernetes.io/hostname: cluster-k-1-control-plane
      containers:
      - name: konga
        image: pantsel/konga
        env:
        - name: NODE_ENV
          value: production
        ports:
        - containerPort: 1337
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: konga
  name: konga-svc
  namespace: konga
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1337
      name: http
      nodePort: 30008
  type: NodePort
  selector:
    app: konga
---

#kind: Ingress
#apiVersion: networking.k8s.io/v1
#metadata:
#  name: konga-ingress
#  namespace: konga
#  annotations:
#    spec.ingressClassName: nginx
#    nginx.ingress.kubernetes.io/ssl-redirect: "true"
#spec:
#  rules:
#  - host: konga.localhost.serge
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: konga-svc
#            port:
#              number: 80
#  tls:
#    - hosts:
#      - konga.localhost.serge
#      secretName: certificate-secret

---